"use client";

import Link from "next/link";
import { useState } from "react";

type Snapshot = { client: { id: string; name: string; company: string; status: string; notes: string }; cases: Array<{ id: string; title: string; module: string; status: string; current_revision: number; updated_at: string }>; outcomes: Array<{ case_id: string; next_action: string; blockers: string; actual_result: string; follow_up_date: string | null }>; sources: Array<{ case_id: string; id: string }>; audit: Array<{ id: number; event_type: string; created_at: string }> };

export function ClientSnapshot({ snapshot, locale = "en", demo = false }: { snapshot: Snapshot; locale?: "en" | "zh-Hant"; demo?: boolean }) {
  const zh = locale === "zh-Hant";
  const [name, setName] = useState(snapshot.client.name); const [company, setCompany] = useState(snapshot.client.company); const [notes, setNotes] = useState(snapshot.client.notes); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function update() { setBusy(true); setMessage(""); if (demo) { setMessage(zh ? "示範模式：變更只在這個瀏覽器分頁顯示，不會儲存。" : "Demo mode: the change is shown in this browser tab only and is not stored."); setBusy(false); return; } try { const response = await fetch(`/api/clients/${snapshot.client.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, company, notes }) }); setMessage(response.ok ? (zh ? "已更新。" : "Updated.") : (zh ? "更新失敗。" : "Update failed.")); } finally { setBusy(false); } }
  async function archive() { setBusy(true); setMessage(""); if (demo) { setMessage(zh ? "示範模式：不會封存示範資料，這個動作只作展示。" : "Demo mode: demo records are never archived; this action is illustrative only."); setBusy(false); return; } try { const response = await fetch(`/api/clients/${snapshot.client.id}`, { method: "DELETE" }); setMessage(response.ok ? (zh ? "已封存。" : "Archived.") : (zh ? "封存失敗。" : "Archive failed.")); } finally { setBusy(false); } }
  const outcomeByCase = new Map(snapshot.outcomes.map((item) => [item.case_id, item]));
  return <section className="portal-panel client-snapshot" aria-labelledby="client-snapshot-title"><div className="artifact-heading"><div><p className="portal-kicker">{zh ? "客戶快照" : "Client snapshot"}</p><h1 id="client-snapshot-title">{snapshot.client.name}</h1><p>{snapshot.client.company}</p></div><span className="case-status status-working"><i />{snapshot.client.status}</span></div><div className="client-edit-grid"><label>{zh ? "名稱" : "Name"}<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>{zh ? "公司" : "Company"}<input value={company} onChange={(event) => setCompany(event.target.value)} /></label><label>{zh ? "備註" : "Notes"}<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} maxLength={5000} /></label><div className="button-row"><button type="button" className="portal-primary-button" onClick={update} disabled={busy || !name.trim()}>{zh ? "儲存變更" : "Save changes"}</button><button type="button" className="portal-secondary-button" onClick={archive} disabled={busy}>{zh ? "封存客戶" : "Archive client"}</button></div>{message ? <p role="status">{message}</p> : null}</div><div className="brief-grid"><div><span>{zh ? "個案" : "Cases"}</span><strong>{snapshot.cases.length}</strong></div><div><span>{zh ? "來源" : "Sources"}</span><strong>{snapshot.sources.length}</strong></div><div><span>{zh ? "最近活動" : "Recent audit"}</span><strong>{snapshot.audit.length}</strong></div></div><div className="client-case-list"><h2>{zh ? "已連結個案" : "Linked cases"}</h2>{snapshot.cases.length ? snapshot.cases.map((caseRecord) => { const outcome = outcomeByCase.get(caseRecord.id); return <article key={caseRecord.id}><div><Link href={`/app/cases/${caseRecord.id}`}><strong>{caseRecord.title}</strong></Link><span>{caseRecord.module} · {caseRecord.status} · {zh ? `第 ${caseRecord.current_revision} 稿` : `Revision ${caseRecord.current_revision}`}</span></div><p>{outcome?.next_action ?? (zh ? "尚未有結果下一步" : "No outcome next action yet")}</p>{outcome?.actual_result ? <small>{zh ? "結果：" : "Outcome: "}{outcome.actual_result.slice(0, 280)}</small> : null}{outcome?.blockers ? <small>{zh ? "阻塞：" : "Blocker: "}{outcome.blockers}</small> : null}{outcome?.follow_up_date ? <small>{zh ? "跟進日期：" : "Follow-up: "}{outcome.follow_up_date}</small> : null}</article>; }) : <p>{zh ? "未連結個案。" : "No linked cases."}</p>}</div></section>;
}
