"use client";

import { useState } from "react";

type RequestState = { id: string; status: string; trigger_type: string; result_delta?: { newFacts?: string[]; changedInterpretation?: string[]; contradictions?: string[]; unresolvedGaps?: string[]; recommendedNextAction?: string } | null };

export function ReanalysisPanel({ caseId, initialRequests, locale = "en", demo = false }: { caseId: string; initialRequests: RequestState[]; locale?: "en" | "zh-Hant"; demo?: boolean }) {
  const zh = locale === "zh-Hant"; const [requests, setRequests] = useState(initialRequests); const [busy, setBusy] = useState(false); const latest = requests[0];
  function demoDelta(): RequestState {
    const stamp = new Date().toLocaleTimeString(zh ? "zh-HK" : "en-GB", { hour: "2-digit", minute: "2-digit" });
    return zh
      ? { id: `demo-reanalysis-${stamp}`, status: "completed", trigger_type: "manual", result_delta: { newFacts: ["示範公司 A 已把試用名額由 8 個增至 12 個。", "新增一份公開定價頁，與現有提案的分層說法不一致。"], changedInterpretation: ["原本假設決策者只有一位；來源顯示需要營運同事一併同意。"], contradictions: ["提案寫「兩週交付」，最新會議紀錄寫「四週」。"], unresolvedGaps: ["未有實際轉化數字可驗證成效聲稱。"], recommendedNextAction: `重寫第 4 稿的交付時間與名額數字，再送審批。（示範模式快照 · ${stamp}）` } }
      : { id: `demo-reanalysis-${stamp}`, status: "completed", trigger_type: "manual", result_delta: { newFacts: ["Demo Company A raised the pilot from 8 to 12 places.", "A new public pricing page contradicts the tiering in the current proposal."], changedInterpretation: ["The intake assumed one decision maker; sources show operations has to agree too."], contradictions: ["Proposal says two-week delivery; the latest meeting note says four weeks."], unresolvedGaps: ["No conversion figures yet to support the outcome claim."], recommendedNextAction: `Rewrite revision 4 with the corrected timeline and pilot count, then send for approval. (Demo snapshot · ${stamp})` } };
  }
  async function enqueue(process = false) { setBusy(true); if (demo) { const delta = demoDelta(); window.setTimeout(() => { setRequests([delta]); setBusy(false); }, 900); return; } try { const response = await fetch(`/api/cases/${caseId}/reanalysis`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ triggerType: "manual", process }) }); const value = await response.json() as { request?: RequestState }; if (response.ok && value.request) setRequests([value.request, ...requests.filter((item) => item.id !== value.request?.id)]); } finally { setBusy(false); } }
  return <section className="portal-panel reanalysis-panel" aria-labelledby="reanalysis-title"><div className="artifact-heading"><div><p className="portal-kicker">{zh ? "新資料審閱" : "New information"}</p><h2 id="reanalysis-title">{zh ? "需要調查的新資訊" : "New information needs investigation"}</h2></div></div>{latest ? <><p>{latest.status === "completed" ? (zh ? "差異已準備好供你比較。" : "A delta is ready to compare.") : latest.status === "queued" || latest.status === "running" ? (zh ? "已排入分析；請明確開始處理。" : "Queued for analysis; start processing explicitly.") : latest.status}</p>{latest.result_delta ? <div className="reanalysis-delta"><h3>{zh ? "差異摘要" : "Delta"}</h3>{renderList(zh ? "新事實" : "New facts", latest.result_delta.newFacts)}{renderList(zh ? "解讀變化" : "Changed interpretation", latest.result_delta.changedInterpretation)}{renderList(zh ? "矛盾" : "Contradictions", latest.result_delta.contradictions)}{renderList(zh ? "未解缺口" : "Unresolved gaps", latest.result_delta.unresolvedGaps)}<p><strong>{zh ? "建議下一步" : "Recommended next action"}:</strong> {latest.result_delta.recommendedNextAction}</p></div> : null}</> : <p>{zh ? "來源狀態變更時會建立可去重的審閱請求。" : "An idempotent review request appears when source state changes."}</p>}<div className="button-row"><button type="button" className="portal-secondary-button" onClick={() => enqueue(false)} disabled={busy}>{busy ? (zh ? "排入中…" : "Queueing…") : (zh ? "重新檢查新資料" : "Queue reanalysis")}</button>{latest?.status === "queued" ? <button type="button" className="portal-primary-button" onClick={() => enqueue(true)} disabled={busy}>{zh ? "開始分析" : "Process reanalysis"}</button> : null}</div></section>;
}

function renderList(label: string, values?: string[]) { return values?.length ? <div><strong>{label}</strong><ul>{values.map((value) => <li key={value}>{value}</li>)}</ul></div> : null; }
